<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendudukSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $items = [
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301010101800001',
                'nama_lengkap' => 'Lorem Ipsum A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1980-01-01',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Lorem Ipsum B',
                'nama_ibu' => 'Lorem Ipsum C',
                'no_telepon' => '080000000001',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301014102850002',
                'nama_lengkap' => 'Dolor Sit A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1985-02-01',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Dolor Sit B',
                'nama_ibu' => 'Dolor Sit C',
                'no_telepon' => '080000000002',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301011505080003',
                'nama_lengkap' => 'Amet Consectetur A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '2008-05-15',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Pelajar',
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'anak',
                'nama_ayah' => 'Lorem Ipsum A',
                'nama_ibu' => 'Dolor Sit A',
                'no_telepon' => null,
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010002',
                'nik' => '5301010202780004',
                'nama_lengkap' => 'Adipiscing Elit A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1978-02-02',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'katolik',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Adipiscing Elit B',
                'nama_ibu' => 'Adipiscing Elit C',
                'no_telepon' => '080000000004',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010002',
                'nik' => '5301014203820005',
                'nama_lengkap' => 'Sed Do A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1982-03-02',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'katolik',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Sed Do B',
                'nama_ibu' => 'Sed Do C',
                'no_telepon' => '080000000005',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010003',
                'nik' => '5301010303900006',
                'nama_lengkap' => 'Eiusmod Tempor A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1990-03-03',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'islam',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Eiusmod Tempor B',
                'nama_ibu' => 'Eiusmod Tempor C',
                'no_telepon' => '080000000006',
                'is_asuransi_kesehatan' => false,
            ],
            [
                'no_kk' => '5301010101010003',
                'nik' => '5301014304950007',
                'nama_lengkap' => 'Incididunt Ut A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1995-04-03',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'islam',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Incididunt Ut B',
                'nama_ibu' => 'Incididunt Ut C',
                'no_telepon' => '080000000007',
                'is_asuransi_kesehatan' => false,
            ],
            [
                'no_kk' => '5301010101010004',
                'nik' => '5301010404680008',
                'nama_lengkap' => 'Labore Et A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '1968-04-04',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'smp',
                'pekerjaan' => 'Nelayan',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Labore Et B',
                'nama_ibu' => 'Labore Et C',
                'no_telepon' => '080000000008',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010005',
                'nik' => '5301010505000009',
                'nama_lengkap' => 'Dolore Magna A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '2000-05-05',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Perawat',
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Dolore Magna B',
                'nama_ibu' => 'Dolore Magna C',
                'no_telepon' => '080000000009',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010005',
                'nik' => '5301010606240010',
                'nama_lengkap' => 'Aliqua Minim A',
                'tempat_lahir' => 'XXXXX',
                'tanggal_lahir' => '2024-06-06',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'tidak_sekolah',
                'pekerjaan' => null,
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'anak',
                'nama_ayah' => 'Aliqua Minim B',
                'nama_ibu' => 'Dolore Magna A',
                'no_telepon' => null,
                'is_asuransi_kesehatan' => true,
            ],
        ];

        foreach ($items as $item) {
            $keluargaId = DB::table('keluarga')
                ->where('no_kk', $item['no_kk'])
                ->value('id');

            DB::table('penduduk')->updateOrInsert(
                ['nik' => $item['nik']],
                [
                    'keluarga_id' => $keluargaId,
                    'nama_lengkap' => $item['nama_lengkap'],
                    'tempat_lahir' => $item['tempat_lahir'],
                    'tanggal_lahir' => $item['tanggal_lahir'],
                    'jenis_kelamin' => $item['jenis_kelamin'],
                    'agama' => $item['agama'],
                    'pendidikan_terakhir' => $item['pendidikan_terakhir'],
                    'pekerjaan' => $item['pekerjaan'],
                    'status_perkawinan' => $item['status_perkawinan'],
                    'status_hubungan_keluarga' => $item['status_hubungan_keluarga'],
                    'kewarganegaraan' => 'WNI',
                    'golongan_darah' => null,
                    'no_paspor' => null,
                    'no_kitas_kitap' => null,
                    'nama_ayah' => $item['nama_ayah'],
                    'nama_ibu' => $item['nama_ibu'],
                    'no_telepon' => $item['no_telepon'],
                    'is_asuransi_kesehatan' => $item['is_asuransi_kesehatan'],
                    'is_disabilitas' => false,
                    'jenis_disabilitas' => null,
                    'status' => 'aktif',
                    'keterangan' => null,
                    'deleted_at' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}