<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendudukSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $items = [
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301010101800001',
                'nama_lengkap' => 'Yohanes Manafe',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1980-01-01',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Paulus Manafe',
                'nama_ibu' => 'Maria Manafe',
                'no_telepon' => '081200000001',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301014102850002',
                'nama_lengkap' => 'Martha Manafe',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1985-02-01',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Petrus Neno',
                'nama_ibu' => 'Yuliana Neno',
                'no_telepon' => '081200000002',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010001',
                'nik' => '5301011505080003',
                'nama_lengkap' => 'Andreas Manafe',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '2008-05-15',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Pelajar',
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'anak',
                'nama_ayah' => 'Yohanes Manafe',
                'nama_ibu' => 'Martha Manafe',
                'no_telepon' => null,
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010002',
                'nik' => '5301010202780004',
                'nama_lengkap' => 'Samuel Benu',
                'tempat_lahir' => 'Soe',
                'tanggal_lahir' => '1978-02-02',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'katolik',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Markus Benu',
                'nama_ibu' => 'Agnes Benu',
                'no_telepon' => '081200000004',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010002',
                'nik' => '5301014203820005',
                'nama_lengkap' => 'Agnes Benu',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1982-03-02',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'katolik',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Lukas Nalle',
                'nama_ibu' => 'Monika Nalle',
                'no_telepon' => '081200000005',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010003',
                'nik' => '5301010303900006',
                'nama_lengkap' => 'Rudi Nope',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1990-03-03',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'islam',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Hasan Nope',
                'nama_ibu' => 'Aminah Nope',
                'no_telepon' => '081200000006',
                'is_asuransi_kesehatan' => false,
            ],
            [
                'no_kk' => '5301010101010003',
                'nik' => '5301014304950007',
                'nama_lengkap' => 'Siti Nope',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1995-04-03',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'islam',
                'pendidikan_terakhir' => 'sma',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'istri',
                'nama_ayah' => 'Ahmad Tallo',
                'nama_ibu' => 'Fatimah Tallo',
                'no_telepon' => '081200000007',
                'is_asuransi_kesehatan' => false,
            ],
            [
                'no_kk' => '5301010101010004',
                'nik' => '5301010404680008',
                'nama_lengkap' => 'Martinus Nalle',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '1968-04-04',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'smp',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Yosef Nalle',
                'nama_ibu' => 'Martha Nalle',
                'no_telepon' => '081200000008',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010005',
                'nik' => '5301010505000009',
                'nama_lengkap' => 'Diana Foes',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '2000-05-05',
                'jenis_kelamin' => 'perempuan',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 's1',
                'pekerjaan' => 'Perawat',
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'kepala_keluarga',
                'nama_ayah' => 'Agustinus Foes',
                'nama_ibu' => 'Maria Foes',
                'no_telepon' => '081200000009',
                'is_asuransi_kesehatan' => true,
            ],
            [
                'no_kk' => '5301010101010005',
                'nik' => '5301010606240010',
                'nama_lengkap' => 'Kevin Foes',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '2024-06-06',
                'jenis_kelamin' => 'laki-laki',
                'agama' => 'kristen',
                'pendidikan_terakhir' => 'tidak_sekolah',
                'pekerjaan' => null,
                'status_perkawinan' => 'belum_kawin',
                'status_hubungan_keluarga' => 'anak',
                'nama_ayah' => 'Yosef Foes',
                'nama_ibu' => 'Diana Foes',
                'no_telepon' => null,
                'is_asuransi_kesehatan' => true,
            ],
        ];

        foreach ($items as $item) {
            $keluargaId = DB::table('keluarga')
                ->where('no_kk', $item['no_kk'])
                ->value('id');

            DB::table('penduduk')->updateOrInsert(
                ['nik' => $item['nik']],
                [
                    'keluarga_id' => $keluargaId,
                    'nama_lengkap' => $item['nama_lengkap'],
                    'tempat_lahir' => $item['tempat_lahir'],
                    'tanggal_lahir' => $item['tanggal_lahir'],
                    'jenis_kelamin' => $item['jenis_kelamin'],
                    'agama' => $item['agama'],
                    'pendidikan_terakhir' => $item['pendidikan_terakhir'],
                    'pekerjaan' => $item['pekerjaan'],
                    'status_perkawinan' => $item['status_perkawinan'],
                    'status_hubungan_keluarga' => $item['status_hubungan_keluarga'],
                    'kewarganegaraan' => 'WNI',
                    'golongan_darah' => null,
                    'no_paspor' => null,
                    'no_kitas_kitap' => null,
                    'nama_ayah' => $item['nama_ayah'],
                    'nama_ibu' => $item['nama_ibu'],
                    'no_telepon' => $item['no_telepon'],
                    'is_asuransi_kesehatan' => $item['is_asuransi_kesehatan'],
                    'is_disabilitas' => false,
                    'jenis_disabilitas' => null,
                    'status' => 'aktif',
                    'keterangan' => null,
                    'deleted_at' => null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        }
    }
}